name: CI 
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  secret_scans:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
      
    - name: Gitleaks scan
      uses: gitleaks/gitleaks-action@v2.3.4

  semgrep_scans:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: semgrep scan
        id: semgrep-scan
        run: |
          mkdir -p semgrep/results
          semgrep --config auto --error --json --output=semgrep/results/semgrep.json
      - name: upload semgrep results
        id: upload-semgrep-results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep/results/

  bandit_scans:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    # needs: secret_scans

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
        
    - name: Install Bandit
      run: pip install bandit 

    - name: Run Bandit Scan
      run: bandit -r -ll -ii -f json -o bandit-report.json . 

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Bandit Artifact
        path: bandit-report.json
  image_scan:
      name: Image Scan
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code 
        uses: actions/checkout@v2
  
      - name: Set up Doccker
        uses: docker-practice/actions-setup-docker@v1
        with: 
          docker_version: "20.10.7"
  
      - name: Docker Build
        run: docker build -f Dockerfile -t myapp:latest .
      
      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.1
        with:
          command: cves
          dockerhub-user: ${{ secrets.DOCKER_USER }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD}}
          image: myapp:latest
          only-severities: critical, high
          exit-code: true
          sarif-file: docker-scout-report.output.json
          
      - name: Upload Artifact Docker Scout report
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with: 
          name: docker-scout-report
          path: docker-scout-report.output.json
        
    
