name: CI 

on: [push]

jobs:
  sast_scans:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
        
    - name: Install Bandit
      run: pip install bandit 

    - name: Run Bandit Scan
      run: bandit -r -ll -ii -f json -o bandit-report.json . 

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Bandit Artifact
        path: bandit-report.json
  image_scan:
      name: Image Scan
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code 
        uses: actions/checkout@v2
  
      - name: Set up Doccker
        uses: docker-practice/actions-setup-docker@v1
        with: 
          docker_version: "20.10.7"
  
      - name: Docker Build
        run: docker build -f Dockerfile -t myapp:latest .
      
      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.1
        with:
          command: quickview,cves
          dockerhub-user: ${{ secrets.DOCKER_USER }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD}}
          image: myapp:latest
          only-severities: critical, high
        
    
